name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:  # Only ONE dependencies section
  flutter:
    sdk: flutter
  lottie: ^2.7.0  # Valid version (latest as of Oct 2023)
  provider: ^6.0.5
  video_player: ^2.8.0
  chewie: ^1.4.0
  flutter_swipe_detector: ^2.0.0
  flutter_cache_manager: ^3.3.0
  cupertino_icons: ^1.0.8
  animated_text_kit: ^4.2.3
  animate_do: ^4.0.0
  flutter_svg: ^2.0.9
  flutter_native_splash: ^2.0.0
  firebase_core: ^2.18.0
  firebase_auth: ^4.11.1
  js: ^0.6.7
  animations: ^2.0.7
  google_fonts: ^3.0.1

dependency_overrides:
  js: 0.6.7
  firebase_core_web: 2.11.3
  firebase_auth_web: 5.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
          weight: 400
        - asset: fonts/Inter-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Bold.ttf
          weight: 700